#!/bin/sh

if [ $# -eq 0 ]
then
	echo "`basename $0` <version>"
	exit 1
fi

bin=`dirname $0`
pwd=`pwd`
cd ~/server

if [ ! -e "$1" ]; then
	echo Version does not exist: exit.
	exit 1
fi

if [ "`$bin/mcshowversion`" = "$1" ]; then
	echo Already current.
	exit 0
fi

if [ -e current ]; then
	echo Different current: stop, change current and start.
	$bin/mcstop
	rm current
else
	echo No current: set version and start.
fi

ln -rs $1 current 
$bin/mcstart

cd $pwd
